Repository hibernate/hibernate-orm, pull requests merged in 2018-09, with the labels that each got.

#2505 HHH-12927 - Immutable warning issued if immutable entities are referenced but not changed during update
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromElement.java
  hibernate-core/src/main/java/org/hibernate/hql/internal/classic/QueryTranslatorImpl.java
  hibernate-core/src/main/java/org/hibernate/hql/spi/QueryTranslator.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeExceptionTest.java
Labels: Ready for integration

#2509 HHH-12929 - Add AtomikosJtaPlatform implementation
  documentation/src/main/asciidoc/userguide/chapters/transactions/Transactions.adoc
  gradle/libraries.gradle
  hibernate-core/hibernate-core.gradle
  hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
  hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/AtomikosJtaPlatform.java
  hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/StandardJtaPlatformResolver.java
  hibernate-core/src/test/java/org/hibernate/test/lazyload/AtomikosJtaLazyLoadingTest.java
Labels: Ready for integration

#2506 HHH-12933 - Generate_statistics grows QueryStatistics ConcurrentHashMap indefinitely
  hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
  hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
  hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
  hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
  hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
  hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
  hibernate-core/src/test/java/org/hibernate/test/stats/ExplicitQueryStatsMaxSizeTest.java
  hibernate-core/src/test/java/org/hibernate/test/stats/QueryStatsMaxSizeTest.java
Labels: Ready for integration

#2519 HHH-12952 - Document the hibernate.statistics.query_max_size behavior and explain its implications
  documentation/src/main/asciidoc/userguide/Hibernate_User_Guide.adoc
  documentation/src/main/asciidoc/userguide/chapters/portability/Portability.adoc
  documentation/src/main/asciidoc/userguide/chapters/statistics/Statistics.adoc
  hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
Labels: Ready for review

#2458 HHH-12855 - Add query plan compilation statistics
  documentation/src/main/asciidoc/userguide/chapters/statistics/Statistics.adoc
  hibernate-core/src/main/java/org/hibernate/engine/query/spi/QueryPlanCache.java
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
  hibernate-core/src/main/java/org/hibernate/stat/QueryStatistics.java
  hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
  hibernate-core/src/main/java/org/hibernate/stat/internal/QueryStatisticsImpl.java
  hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
  hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java
  hibernate-core/src/test/java/org/hibernate/stat/internal/ConcurrentQueryStatisticsTest.java
  hibernate-core/src/test/java/org/hibernate/stat/internal/QueryPlanCacheStatisticsTest.java
Labels: Ready for review

#2522 HHH-12957 - Calling custom functions in JPQL with the function() is missing in the documentation
  documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
  documentation/src/test/java/org/hibernate/userguide/hql/PostgreSQLFunctionSelectClauseTest.java
  documentation/src/test/java/org/hibernate/userguide/hql/PostgreSQLFunctionWhereClauseTest.java
Labels: Requires changes

#2339 HHH-12675 - Respect inverse property for JoinedSubclassEntityPersister
  hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/inheritance/joined/JoinedSubclassAndSecondaryTable.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/inheritance/joined/Pool.java
Labels: Ready for review

#2536 HHH-11771 - @Id annotation ignored with @MappedSuperclass inheritance
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassBasicPropertyIdAttributeOverrideTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassIdPropertyBasicAttributeOverrideTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassWithUuidAsBasic.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/SubclassWithUuidAsId.java
Labels: Ready for review
