Repository hibernate/hibernate-orm, pull requests merged in 2018-02, with the labels that each got.

#2117 HHH-12141 - SQL insert in stateless session causes javax.persistence.TransactionRequiredException
  hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
  hibernate-core/src/test/java/org/hibernate/test/stateless/StatelessSessionTest.java
Labels: Requires clarifications

#2145 HHH-11901 - Fix auditing collections that contain null values.
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/AbstractCollectionMapper.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/BasicCollectionMapper.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ListCollectionMapper.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/MapCollectionMapper.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/initializor/ListCollectionInitializor.java
  hibernate-envers/src/test/java/org/hibernate/envers/test/integration/collection/CollectionNullValueTest.java
Labels: Ready for review

#2159 HHH-11981 - Fix QueryException thrown for association queries using EntitiesModifiedAtRevision queries.
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesModifiedAtRevisionQuery.java
  hibernate-envers/src/test/java/org/hibernate/envers/test/integration/query/AssociationEntitiesModifiedQueryTest.java
Labels: Ready for integration

#2143 HHH-12260: refactor org.hibernate.event.internal.EvictVisitor#evictCollection
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/EvictVisitor.java
  hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyCollectionDetachTest.java
Labels: Requires clarifications

#2142 HHH-12273 - Load Proxy by its identifier should consider the Session UUID
  hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/ops/GetLoadJpaComplianceDifferentSessionsTest.java
Labels: Ready for review

#2144 HHH-12230 - SelectCase does not work when simultaneously exists in select and group by sections
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaSubqueryImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/QueryStructure.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/Renderable.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/RenderingContext.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/BinaryArithmeticOperation.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/CoalesceExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/CompoundSelectionImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ConcatExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/EntityTypeExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ListIndexExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/LiteralExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/NullifExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ParameterExpressionImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/PathTypeExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SearchedCaseExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SimpleCaseExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SizeOfPluralAttributeExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SubqueryComparisonModifierExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/UnaryArithmeticOperation.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/function/BasicFunctionExpression.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractFromImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractPathImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/RootImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/AbstractSimplePredicate.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/CompoundPredicate.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/NegatedPredicateWrapper.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/selectcase/GroupBySelectCaseTest.java
Labels: Ready for review

#2128 HHH-9460 - Removing non-optional bidirectional @OneToOne association with cascade
  hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/derivedidentities/e4/b/MedicalHistory.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OneToOneMapsIdJoinColumnTest.java
  hibernate-core/src/test/java/org/hibernate/test/onetoone/optional/BidirectionalOptionalOneToOneTest.java
Labels: Ready for review, Requires Gail

#2163 HHH-12297 - Relations are not loaded when using Fetch Profiles
  hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java
  hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
  hibernate-core/src/main/java/org/hibernate/type/EntityType.java
  hibernate-core/src/main/java/org/hibernate/type/Type.java
  hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/CollectionLoadedInTwoPhaseLoadTest.java
  hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/EntityLoadedInTwoPhaseLoadTest.java
  hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/join/JoinFetchProfileTest.java
Labels: Ready for review
