Repository hibernate/hibernate-orm, pull requests merged in 2018-11, with the labels that each got.

#2615 HHH-11096 - @CreationTimestamp doesn't works with @Column(nullable=false)
  hibernate-core/src/main/java/org/hibernate/engine/internal/Nullability.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/DatabaseCreationTimestampNullableColumnTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/InMemoryCreationTimestampNullableColumnTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/UpdateTimestampTest.java
  hibernate-core/src/test/java/org/hibernate/test/legacy/Custom.hbm.xml
Labels: Ready for review

#2632 HHH-12964 - Upgrade to dom4j 2.1.1 - 5.2
  libraries.gradle
Labels: 5.2

#2624 HHH-13077 - Optimize query plan call count
  hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
  hibernate-core/src/main/java/org/hibernate/query/Query.java
  hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
  hibernate-core/src/main/java/org/hibernate/query/internal/QueryImpl.java
  hibernate-core/src/test/java/org/hibernate/stat/internal/QueryPlanCacheStatisticsTest.java
Labels: 5.4, Ready for review, Requires Steve

#2639 HHH-12925 - The JDBC Type to Hibernate matching is limited to the Dialect only instead of considering the Type contributions as well
  hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
  hibernate-core/src/main/java/org/hibernate/loader/custom/JdbcResultMetadata.java
  hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/PostgreSQLMultipleTypesOtherContributorTest.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/Event.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/Inet.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetJavaTypeDescriptor.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetSqlTypeDescriptor.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetType.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/PostgreSQLInetTypesOtherContributorTest.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/PostgreSQLInetTypesOtherTest.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/Json.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonJavaTypeDescriptor.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonSqlTypeDescriptor.java
  hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonType.java
  hibernate-core/src/test/java/org/hibernate/test/id/uuid/PostgreSQLUUIDGeneratedValueTest.java
  hibernate-core/src/test/java/org/hibernate/test/type/contributor/ArrayTypeContributorTest.java
Labels: Ready for integration

#2644 HHH-13101 - Document `hibernate.id.disable_delayed_identity_inserts`
  documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc
  migration-guide.adoc
Labels: Ready for review

#2571 HHH-12374 HHH-12380
  hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
  hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingHasParentTest.java
Labels: 5.1, Requires Gail

#2646 HHH-13105 - Add registries for user-defined Types as currently a custom Type is instantiated and configured 9 times
  hibernate-core/src/main/java/org/hibernate/type/TypeFactory.java
  hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
  hibernate-core/src/test/java/org/hibernate/test/type/contributor/ArraySpyType.java
  hibernate-core/src/test/java/org/hibernate/test/type/contributor/CustomTypeInstanceCountTest.java
Labels: Ready for review

#2659 HHH-13111 Restore support of criteria subqueries in select clauses
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaSubqueryImpl.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/AbstractSubqueryInSelectClauseTest.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/SubqueryInSelectClauseJpaComplianceTest.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/SubqueryInSelectClauseTest.java
Labels: 5.4, Ready for review
