Repository hibernate/hibernate-orm, pull requests merged in 2019-02, with the labels that each got.

#2740 HHH-6190 - Leverage JmxService to expose management and monitoring capabilities.
  documentation/src/test/java/org/hibernate/userguide/jmx/JmxTest.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchBuilderImpl.java
  hibernate-core/src/main/java/org/hibernate/jmx/internal/JmxServiceImpl.java
  hibernate-core/src/main/java/org/hibernate/service/spi/Manageable.java
  hibernate-core/src/main/java/org/hibernate/service/spi/OptionallyManageable.java
  hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
  hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
Labels: Ready for review

#2754 HHH-13227 - UnsupportedOperationException when programmatically overriding hibernate.ejb.cfgfile
  hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
  hibernate-core/src/test/java/org/hibernate/cfg/CfgFilePropertyTest.java
Labels: Ready for review

#2756 HHH-13230 - The AvailableSettings.HBM2DDL_HALT_ON_ERROR setting does not accept String values
  hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/SchemaScriptFileGenerationFailureTest.java
Labels: Ready for review

#2777 HHH-13256 - Fix the fieldsPreUpdateNeeded property index allocation in AbstractEntityPersister#update
  hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/InMemoryCreationTimestampNullableColumnTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/InMemoryUpdateTimestampTest.java
Labels: Ready for review

#2755 HHH-13228 - The modification of a @OneToOne with @MapsId property is silently ignored during a merge operation
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OneToOneMapsIdChangeParentTest.java
Labels: Ready for review

#2778 HHH-13217 - Don't throw exception if both @MappedSuperclass and @Inheritance are used
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
  hibernate-core/src/test/java/org/hibernate/test/inheritance/MappedSuperclassInheritanceTest.java
Labels: Ready for review

#2786 HHH-13254 Upgrade Agroal to 1.4
  gradle/libraries.gradle
Labels: 5.4, Ready for review

#2782 HHH-13269 - Embeddable collection regression due to HHH-11544
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
  hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/LoadQueryJoinAndFetchProcessor.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/mapping/NestedEmbeddableTest.java
Labels: 5.4, Ready for review

#2788 HHH-13281 - Avoid ClassCastException when unwrapping EntityManager to deprecated org.hibernate.ejb.HibernateEntityManager.
  hibernate-core/src/main/java/org/hibernate/jpa/spi/HibernateEntityManagerImplementor.java
  hibernate-core/src/test/java/org/hibernate/test/jpa/EntityManagerUnwrapTest.java
Labels: 5.4

#2794 HHH-13285 : ClassCastException: org.dom4j.DocumentFactory cannot be cast to org.dom4j.DocumentFactory after dom4j update
  hibernate-core/src/main/java/org/hibernate/internal/util/xml/XMLHelper.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/reflection/JPAOverriddenAnnotationReaderTest.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/reflection/XMLContextTest.java
  hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/EnversServiceImpl.java
Labels: 5.4
