Repository hibernate/hibernate-orm, pull requests merged in 2019-03, with the labels that each got.

#2792 HHH-13277 Make HibernateMethodLookupDispatcher less fragile
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/HibernateMethodLookupDispatcher.java
Labels: 5.4

#2801 HHH-13217 - Don't throw exception if both @MappedSuperclass and @Inheritance are used
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
  hibernate-core/src/test/java/org/hibernate/test/inheritance/MappedSuperclassInheritanceTest.java
Labels: Ready for review

#2799 HHH-13241 Constraint violation when deleting entites in bi-directional, lazy OneToMany association with bytecode enhancement
  hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java
  hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/BidirectionalLazyTest.java
  hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsInEmbeddableTest.java
  hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsTest.java
Labels: 5.4, Ready for review

#2820 HHH-13324 Install the security manager check layer once and for all
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
Labels: 5.4
