Repository hibernate/hibernate-orm, pull requests merged in 2019-01, with the labels that each got.

#2731 HHH-13165 - Don't use confusing "this" in the User Guide admonition blocks
  documentation/src/main/asciidoc/userguide/appendices/Legacy_Bootstrap.adoc
  documentation/src/main/asciidoc/userguide/appendices/Legacy_Native_Queries.adoc
  documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
  documentation/src/main/asciidoc/userguide/chapters/bootstrap/Bootstrap.adoc
  documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/access.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/associations.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/dynamic_model.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/embeddables.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/immutability.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/inheritance.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/naming.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/natural_id.adoc
  documentation/src/main/asciidoc/userguide/chapters/domain/types.adoc
  documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
  documentation/src/main/asciidoc/userguide/chapters/events/Events.adoc
  documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
  documentation/src/main/asciidoc/userguide/chapters/flushing/Flushing.adoc
  documentation/src/main/asciidoc/userguide/chapters/jdbc/Database_Access.adoc
  documentation/src/main/asciidoc/userguide/chapters/multitenancy/MultiTenancy.adoc
  documentation/src/main/asciidoc/userguide/chapters/pc/BytecodeEnhancement.adoc
  documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
  documentation/src/main/asciidoc/userguide/chapters/portability/Portability.adoc
  documentation/src/main/asciidoc/userguide/chapters/query/criteria/Criteria.adoc
  documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
  documentation/src/main/asciidoc/userguide/chapters/query/native/Native.adoc
  documentation/src/main/asciidoc/userguide/chapters/schema/Schema.adoc
  documentation/src/main/asciidoc/userguide/chapters/transactions/Transactions.adoc
  documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
Labels: 5.4.1, Requires changes

#2728 HHH-13197 Reduce bootstrap log verbosity
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/EnhancerImpl.java
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
Labels: 5.4.1, Ready for review

#2726 HHH-13068 - "order_inserts = true" causes FK Violation when inserting Self Referential Entity with Single_Table Inherited Entities
  hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
  hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingSelfReferenceSingleTableInheritance.java
Labels: Ready for review

#2737 HHH-13210 Don't log about running a script of type ScriptSourceInputN…
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/AbstractScriptSourceInput.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromFile.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromReader.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromUrl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/spi/ScriptSourceInput.java
Labels: 5.4.1, Ready for review

#2738 HHH-13211 Reduce logging verbosity of QueryTranslatorFactoryInitiator
  hibernate-core/src/main/java/org/hibernate/hql/internal/QueryTranslatorFactoryInitiator.java
  hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
Labels: 5.4.1, Ready for review

#2733 HHH-13202 - Add support for PostgreSQL "GENERATED BY DEFAULT AS IDENTITY"
  gradle/databases.gradle
  hibernate-core/src/main/java/org/hibernate/dialect/Database.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL10Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/PostgreSQL10IdentityColumnSupport.java
  hibernate-core/src/test/java/org/hibernate/dialect/resolver/DialectFactoryTest.java
  hibernate-core/src/test/java/org/hibernate/test/id/sequence/PostgreSQLIdentitySequenceTest.java
  hibernate-core/src/test/java/org/hibernate/test/id/sequence/PostgreSQLIdentitySupportTest.java
Labels: Ready for review

#2763 HHH-13239 - The query hint javax.persistence.lock.timeout doesn't work correctly on HANA
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
  hibernate-core/src/test/java/org/hibernate/dialect/HANADialectTestCase.java
Labels: Ready for review

#2757 HHH-13229 - Sequences in MariaDB doesnt work on existing sequence
  gradle/databases.gradle
  hibernate-core/src/main/java/org/hibernate/dialect/MariaDB103Dialect.java
  hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorMariaDBDatabaseImpl.java
  hibernate-core/src/test/java/org/hibernate/id/SequenceValueExtractor.java
  hibernate-core/src/test/java/org/hibernate/test/dialect/functional/SequenceInformationMariaDBTest.java
Labels: Ready for review
