Repository hibernate/hibernate-orm, pull requests merged in 2020-04, with the labels that each got.

#3080 HHH-13689 Replace uses of the deprecated osgi plugin with the biz.aQute.bnd plugin
  build.gradle
  gradle/java-module.gradle
  gradle/published-java-module.gradle
  hibernate-core/hibernate-core.gradle
  hibernate-entitymanager/hibernate-entitymanager.gradle
  hibernate-envers/hibernate-envers.gradle
  hibernate-java8/hibernate-java8.gradle
  hibernate-osgi/hibernate-osgi.gradle
Labels: Depends on another PR

#3318 wip/6.0 Update user guide regarding @SortNatural by default
  documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
Labels: 6.0

#3339 HHH-13937 Get rid of junit5 compile-time dependencies
  hibernate-core/hibernate-core.gradle
  hibernate-orm-modules/src/test/java/org/hibernate/wildfly/integrationtest/HibernateEnversOnWildflyTest.java
  hibernate-testing/hibernate-testing.gradle
Labels: 6.0

#3342 HHH-13682 Follow-up: restore the "net.bytebuddy.experimental" system property for JDK15+
  gradle/java-module.gradle
Labels: 5.5, Trivial and ready for integration

#3345 HHH-13953 (5.4)
  gradle/libraries.gradle
Labels: 5.4

#3314 wip/6.0 Fix a regular expression sloppiness in IndexQueryHintHandler
  hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java
Labels: 6.0

#3308 wip/6.0 Loader 'readOnly' support
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderDynamicBatch.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderProvidedQueryImpl.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/spi/CollectionLoader.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleEntityLoader.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleIdEntityLoader.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleUniqueKeyEntityLoader.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/main/java/org/hibernate/query/internal/ScrollableResultsIterator.java
  hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptions.java
  hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptionsAdapter.java
  hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/loading/ReadonlyHintTest.java
Labels: 6.0

#3362 wip/6.0 AST tree logging line separator OS agnostic
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/SqlTreePrinter.java
Labels: 6.0

#3341 HHH-13916 : Add a unique Session "token"
  hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
  hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
Labels: 6.0

#3354 wip/6.0 Implement filter for HQL/Criteria
  documentation/src/test/java/org/hibernate/userguide/pc/FilterJoinTableTest.java
  documentation/src/test/java/org/hibernate/userguide/pc/FilterTest.java
  hibernate-core/src/main/java/org/hibernate/internal/FilterHelper.java
  hibernate-core/src/main/java/org/hibernate/internal/FilterJdbcParameter.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderBatchKey.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/StandardSqmSelectTranslator.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstWalker.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/spi/StandardSqlAstSelectTranslator.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/tree/predicate/FilterPredicate.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/tree/select/QuerySpec.java
  hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcSelect.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterBasicsTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterJoinTableTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterOnJoinFetchedCollectionTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterWithSqlFragmentAliasTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterBasicsTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterJoinTableTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterOnJoinFetchedCollectionTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterWithSqlFragmentAliasTests.java
Labels: 6.0

#3364 Add rollup() and cube() for use in group by clause
  hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
  hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
  hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
  hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Labels: 6.0

#3374 wip/6.0 Improve performance via Collections.addAll
  hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java
  hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java
  hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
  hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
Labels: 6.0

#3382 HHH-13695 DDL export forgets to close a Statement (5.3)
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/GenerationTargetToDatabase.java
Labels: 5.3, Requires Gail
