Repository hibernate/hibernate-orm, pull requests merged in 2021-12, with the labels that each got.

#4405 Wip/6.0 natural id
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SimpleNaturalIdLoader.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/ClassWithIdentityColumn.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/Group.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/ImmutableNaturalIdTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/MutableNaturalIdTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/User.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/User.java
Labels: 6.0

#4384 Improve reliability of ProposedGeneratedTests
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/temporals/ProposedGeneratedTests.java
Labels: 6.0

#4408 Fix test failures for MySql, Derby and Sybase
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/cid/idclass/NestedIdClassTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/cid/nonaggregated/SmokeTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/instantiator/embeddable/Name.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/instantiator/embedded/Name.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/instantiator/registered/Name.java
Labels: 6.0

#4412 Revert deprecations on main
  hibernate-core/src/main/java/org/hibernate/EntityMode.java
  hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
  hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/internal/EntityModeConverter.java
  hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/AbstractEntitySourceImpl.java
  hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
  hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
  hibernate-core/src/main/java/org/hibernate/tuple/Tuplizer.java
  hibernate-core/src/main/java/org/hibernate/tuple/component/ComponentTuplizer.java
  hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityTuplizer.java
Labels: 5.6

#4416 Wip/6.0 ToOneAttributeMapping#bidirectionalAttributeName value determination
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
  hibernate-core/src/main/java/org/hibernate/property/access/spi/SetterFieldImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultCreationState.java
  hibernate-core/src/test/java/org/hibernate/orm/test/loading/LoadContainedInDoubleContainingTest.java
Labels: 6.0

#4415 HHH-14897 Allow ordering with nulls first/last in JPA Criteria
  hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaBuilderImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaQueryImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/OrderImpl.java
  hibernate-core/src/test/java/org/hibernate/query/criteria/internal/NullPrecedenceTest.java
Labels: 5.6

#4345 HHH-14211 Switch to using oid for CLOB in PostgreSQL to avoid losing data after vacuumlo
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java
  hibernate-core/src/test/java/org/hibernate/test/lob/PostgreSqlLobStringTest.java
  migration-guide.adoc
Labels: 5.6

#4420 HHH-14211 Switch to using oid for CLOB in PostgreSQL to avoid losing data after vacuumlo
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/test/java/org/hibernate/orm/test/lob/PostgreSqlLobStringTest.java
Labels: 6.0

#4423 Fix IdentifiableType#getId(Class<Y> type) failing for primitive types
  hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/metamodel/EmbeddedTypeTest.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/metamodel/JpaMetamodelDisabledPopulationTest.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/metamodel/JpaMetamodelEnabledPopulationTest.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/metamodel/JpaMetamodelskipUnsupportedPopulationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/AbstractCriteriaTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaCompilingTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ManipulationCriteriaTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/OnKeywordTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/QueryBuilderTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatKeywordTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/AggregationResultTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/CastTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/ExpressionsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/ListIndexTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/PredicateTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/idclass/IdClassPredicateTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/mapjoin/MapJoinTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/AbstractPathImplTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/FetchAndJoinTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/PluralAttributeExpressionsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/subquery/CorrelatedSubqueryTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/subquery/UncorrelatedSubqueryTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/tuple/TupleCriteriaTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/AbstractJpaMetamodelPopulationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/AbstractMetamodelSpecificTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Alias.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Article.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/BaseEmbeddedEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Country.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/CreditCard.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Customer.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/EmbeddedTypeTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Entity1.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Entity2.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Entity3.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Info.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/LineItem.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/MapEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/MapEntityLocal.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Order.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Person.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Phone.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Product.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/ShelfLife.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Spouse.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Thing.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/ThingWithQuantity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/Translation.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/VersionedEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/RootEntityTypeModelTest.java
Labels: 6.0

#4410 Wip/6.0 element collection
  hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
  hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/LoadEntityWithElementCollectionTest.java
Labels: 6.0

#4393 fix the signature of Session.merge()
  hibernate-core/src/main/java/org/hibernate/Session.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
Labels: 6.0

#4432 improve the javadoc for AttributeBinder+AttributedBinderType
  hibernate-core/src/main/java/org/hibernate/annotations/AttributeBinderType.java
  hibernate-core/src/main/java/org/hibernate/tuple/AttributeBinder.java
Labels: 6.0

#4435 remove left-behind method createSQLQuery() from StatelessSession
  hibernate-core/src/main/java/org/hibernate/StatelessSession.java
  hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionTest.java
Labels: 6.0

#4439 Cache and expose column size to get the (default and non-default) scale
  hibernate-core/src/main/java/org/hibernate/mapping/Column.java
Labels: 6.0

#4469 clean up version stuff in DB2i/z dialects
  hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/DB2iSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/DB2zSqlAstTranslator.java
Labels: 6.0

#4464 @FailureExpected annotation added to tests in orm 6 substituted with @NotImplementedYet
  hibernate-core/src/test/java/org/hibernate/orm/test/annotations/entity/BasicHibernateAnnotationsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/attributeOverrides/PluralEmbeddedOverrideTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/attributeOverrides/TablePerClassOverrideTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/LoadPlanBuilderTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/BasicCriteriaUsageTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CachedQueryTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/size/ManyToManySizeTest2.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/exec/DiscriminatorTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithLazyManyToOneSelfReferenceTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithManyToOneSelfReferenceTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/db2/DB2CustomSQLTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/derby/DerbyCustomSQLTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/mysql/MySQLCustomSQLTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/oracle/OracleCustomSQLTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/sqlserver/SQLServerCustomSQLTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/sybase/SybaseCustomSQLTest.java
Labels: 6.0

#4478 HHH-8051 Gracefully handle not-found to-one associations
  documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
  hibernate-envers/src/main/java/org/hibernate/envers/Audited.java
  hibernate-envers/src/main/java/org/hibernate/envers/RelationTargetNotFoundAction.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/Configuration.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/EnversSettings.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/ClassesAuditingData.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/ToOneRelationMetadataGenerator.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ToOneIdMapper.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundConfigTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundLegacyTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundTest.java
Labels: Envers, 6.0

#4477 HHH-11735 Support traversal of to-many-associations in audit queries.
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MiddleTableCollectionMetadataGenerator.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/EntityConfiguration.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/RelationDescription.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/CriteriaTools.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/NotNullAuditExpression.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/NullAuditExpression.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/RelatedAuditEqualityExpression.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/RelatedAuditInExpression.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/SimpleAuditExpression.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java
  hibernate-envers/src/test/java/org/hibernate/envers/test/integration/dynamic/AuditedDynamicComponentsAdvancedCasesTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/dynamic/SanityCheckTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationToManyJoinQueryTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationToNotAuditedManyJoinQueryTest.java
Labels: Envers, 6.0

#4476 clean up the Dialect-specific default property handling
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CUBRIDDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CacheDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/IngresDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MaxDBDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MimerSQLDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseAnywhereDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/sql/exec/internal/StandardJdbcMutationExecutor.java
Labels: 6.0

#4481 HHH-14981 Support null precedence with Envers Query API
  hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/QueryBuilder.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/order/AuditOrder.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/order/NullPrecedence.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/order/internal/PropertyAuditOrder.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/NullPrecedenceTest.java
Labels: Envers, 6.0

#4472 Reenable additional tests
  hibernate-core/src/test/java/org/hibernate/orm/test/subquery/EntityA.java
  hibernate-core/src/test/java/org/hibernate/orm/test/subquery/SubqueryTest.java
  hibernate-core/src/test/java/org/hibernate/test/subquery/SubqueryTest.java
Labels: 6.0

#4485 Fix instantiation of VirtualId
  hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
  hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorProxied.java
  hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdRepresentationStrategy.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/cid/AbstractCompositeIdTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/cid/Mappings.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/cid/MyInterface.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/cid/MyInterfaceImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/AbstractComponentPropertyRefTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/AddressImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/Mappings.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/Server.java
  hibernate-core/src/test/java/org/hibernate/orm/test/abstractembeddedcomponents/propertyref/ServerImpl.java
  hibernate-core/src/test/java/org/hibernate/test/abstractembeddedcomponents/cid/AbstractCompositeIdTest.java
  hibernate-core/src/test/java/org/hibernate/test/abstractembeddedcomponents/propertyref/AbstractComponentPropertyRefTest.java
Labels: 6.0

#3175 HHH-13817 Support to-one traverseRelations for RevisionsOfEntity queries
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditAssociationQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesAtRevisionAssociationQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesAtRevisionQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesModifiedAtRevisionQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityAssociationQuery.java
  hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/BaseEnversFunctionalTestCase.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationRevisionsOfEntitiesQueryStoreAtDeletionTest.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationRevisionsOfEntitiesQueryTest.java
Labels: Envers, 6.0

#4489 Wip/6.0 fix Stack Overflow with EntitySelectFetchByUniqueKeyInitializer
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValuesSourceProcessingState.java
  hibernate-core/src/main/java/org/hibernate/sql/results/spi/LoadContexts.java
  hibernate-core/src/test/java/org/hibernate/orm/test/fetch/OneToOneOwnerByContainedEagerCyclesTest.java
Labels: 6.0

#4448 documentation surrounding @Lob and Length
  documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
Labels: 6.0

#4484 treat integral types as equivalent for purposes of schema validation
  hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaTypeDescriptor.java
Labels: 6.0

#4493 Upgrades
  gradle/libraries.gradle
Labels: 6.0

#4392 proposed API for instantiation of detached collections
  hibernate-core/src/main/java/org/hibernate/Hibernate.java
  hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedMap.java
  hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedSet.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/DetachedCollectionTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/Many.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/One.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/Several.java
Labels: 6.0

#4495 HHH-11595 Introduce `CollectionAuditTable` support
  documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
  hibernate-envers/src/main/java/org/hibernate/envers/CollectionAuditTable.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AbstractMetadataGenerator.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MiddleTableCollectionMetadataGenerator.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java
Labels: Envers, 6.0

#4502 Fix instantiation of composite property ref
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
  hibernate-core/src/main/java/org/hibernate/query/results/complete/EntityResultImpl.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/SqmMapEntryResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicFetch.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/CollectionDomainResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionAssembler.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SelectEagerCollectionFetch.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedResultImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultJoinedSubclassImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/ArgumentDomainResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/tuple/TupleResult.java
  hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/StandardJdbcValuesMapping.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cuk/Account.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cuk/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cuk/CompositePropertyRefTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cuk/Person.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/cuk/Person.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SmokeTests.java
  hibernate-core/src/test/java/org/hibernate/test/cuk/CompositePropertyRefTest.java
Labels: 6.0

#4333 Log first Exception when MappingModelCreationProcess cannot complete
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationProcess.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
Labels: 6.0

#4504 Wip/6.0 collection element orderby
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/CollectionPartPath.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/PluralAttributePath.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/test/java/org/hibernate/test/joinfetch/JoinFetchTest.java
Labels: 6.0

#4510 Set correct key type if !referenceToPrimaryKey
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
  hibernate-core/src/test/java/org/hibernate/orm/test/uniquekey/NaturalIdCachingTest.java
Labels: 6.0

#4513 Fix test to follow 6.0 behaviour
  hibernate-core/src/test/java/org/hibernate/orm/test/ternary/Employee.java
  hibernate-core/src/test/java/org/hibernate/orm/test/ternary/Site.java
  hibernate-core/src/test/java/org/hibernate/orm/test/ternary/Ternary.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/ternary/TernaryTest.java
  hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseCoreFunctionalTestCase.java
Labels: 6.0

#4523 HHH-14682: Enable COMMENT ON H2
  hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
Labels: 6.0

#4530 fix the javadoc of Query.getSingleResult()
  hibernate-core/src/main/java/org/hibernate/query/Query.java
  hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
  hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/ExceptionExpectations.java
  hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/QueryExceptionHandlingTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java
Labels: 6.0

#4532 more cleanups to the Javadoc for Query
  hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AllowableParameterType.java
  hibernate-core/src/main/java/org/hibernate/query/Query.java
Labels: 6.0

#4542 fix a broken @see annotation + remove one
  hibernate-core/src/main/java/org/hibernate/transform/ResultTransformer.java
Labels: 6.0

#4538 remove some obsolete code from AnnotationBinder
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
Labels: 6.0

#4531 add some overrides that should not be necessary
  hibernate-core/src/main/java/org/hibernate/Session.java
Labels: 6.0
