Repository hibernate/hibernate-orm, pull requests merged in 2021-09, with the labels that each got.

#4170 Fix Metamodel#getEmbeddables() return correct EmbeddableType when mul…
  hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
  hibernate-core/src/test/java/org/hibernate/orm/test/component/AttributeOverridingTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/component/basic/ComponentTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/component/basic/User.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Company.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/EmbeddableMetaModelTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/ILocalizable.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/LocalizedValue.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/MetamodelTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Person.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/ProductEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/WildcardTypeAttributeMetaModelTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/wildcardmodel/AbstractEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/wildcardmodel/AbstractOwner.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/wildcardmodel/EntityOne.java
  hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/wildcardmodel/OwnerOne.java
  hibernate-core/src/test/java/org/hibernate/test/metamodel/MetamodelTest.java
  hibernate-core/src/test/java/org/hibernate/test/metamodel/WildcardTypeAttributeMetaModelTest.java
  migration-guide.adoc
Labels: 6.0

#4181 Fixed and reorganized tests in hibernate-jcache
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/BaseFunctionalTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/DomainDataRegionTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/HibernateCacheTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/InsertedDataTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheClasspathConfigUriTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheConfigRelativePathTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheConfigUrlTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheTransactionalCacheConcurrencyStrategyTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/MissingCacheStrategyTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/RefreshUpdatedDataTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/StorageAccessTest.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/TestHelper.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Account.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Event.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/EventManager.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/HolidayCalendar.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Item.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Person.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/PhoneNumber.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Product.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/UuidItem.java
  hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/VersionedItem.java
  hibernate-jcache/src/test/resources/hibernate-config/domain/Account.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/domain/Event.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/domain/HolidayCalendar.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/domain/Item.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/domain/Person.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/domain/PhoneNumber.hbm.xml
  hibernate-jcache/src/test/resources/hibernate-config/ehcache/jcache-ehcache-config.xml
Labels: 6.0

#4192 insert with @DynamicInsert should use generateIdentityInsertString()
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
Labels: 6.0

#4189 expose two operations on EntityType for use by Hibernate Reactive
  hibernate-core/src/main/java/org/hibernate/type/EntityType.java
Labels: 5.5

#4202 Wip/6.0 merge main
  gradle/libraries.gradle
  hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java
  hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMappingImpl.java
  hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
  hibernate-core/src/main/java/org/hibernate/type/EntityType.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/AddNamedQueryTest.java
  hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/BytecodeEnhancedLazyLoadingOnDeletedEntityTest.java
  hibernate-core/src/test_legacy/org/hibernate/jpa/test/query/AddNamedQueryTest.java
Labels: 6.0

#4206 HHH-14814 Inconsistent rendering of table alias in delete queries
  hibernate-core/src/test/java/org/hibernate/test/hql/DeleteWhereFunctionCallTest.java
Labels: 6.0

#4205 HHH-14763 Avoid suppress exceptions in try/finally
  hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
  hibernate-core/src/main/java/org/hibernate/internal/util/ExceptionHelper.java
  hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/DdlTransactionIsolatorNonJtaImpl.java
  hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java
Labels: 6.0

#4114 [HHH-11755] Drop "Serializable" from the Event Listener interfaces
  hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/AbstractReassociateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPreLoadEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/service/spi/EventListenerGroup.java
  hibernate-core/src/main/java/org/hibernate/event/service/spi/EventListenerRegistry.java
  hibernate-core/src/main/java/org/hibernate/event/spi/AutoFlushEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/ClearEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/DeleteEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/DirtyCheckEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/EvictEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/FlushEntityEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/FlushEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/InitializeCollectionEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/LoadEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/LockEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/MergeEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PersistEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionRecreateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionRemoveEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionUpdateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostDeleteEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostInsertEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostLoadEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostUpdateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionRecreateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionRemoveEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionUpdateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreDeleteEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreInsertEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreLoadEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PreUpdateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/RefreshEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/ReplicateEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/ResolveNaturalIdEventListener.java
  hibernate-core/src/main/java/org/hibernate/event/spi/SaveOrUpdateEventListener.java
Labels: 6.0

#3699 HHH-14413 fix issue that EntityUpdateAction increments version despite veto on update
  hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java
  hibernate-core/src/test/java/org/hibernate/event/PreUpdateEventListenerVetoTest.java
Labels: Impacts Hibernate Reactive

#4203 Fix resolving collection key when creating suffixed fetch builders
  hibernate-core/src/main/java/org/hibernate/query/results/dynamic/DynamicFetchBuilderStandard.java
  hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Account.java
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Group.java
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Person.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Person.java
  hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/PropertyRefTest.java
Labels: 6.0

#4240 Move and adapt tests from sql/storedproc
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/tck2_2/StoredProcedureApiTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/storedproc/H2ProcTesting.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/storedproc/PostgresRefCursorSupportTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/storedproc/ResultMappingTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/storedproc/StoredProcedureResultSetMappingTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/storedproc/StoredProcedureTest.java
  hibernate-core/src/test/java/org/hibernate/test/sql/storedproc/StoredProcedureTest.java
  hibernate-core/src/test_legacy/org/hibernate/test/sql/storedproc/StoredProcedureParameterRegistrationTest.java
Labels: 6.0

#4242 HHH-14840 : IBM Db2 11.1 fails on TransientOverride test cases (5.3)
  hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentJoined.java
  hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentTablePerClass.java
Labels: Requires Gail, 5.3
