Repository hibernate/hibernate-orm, pull requests merged in 2022-10, with the labels that each got.

#5374 HHH-15543 Don't throw CNFE with OracleDialect when JDBC driver classes are invisible
  hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcType.java
Labels: 6.1

#5375 HHH-15548 Fix schema validation issues on PostgreSQL with Instant type
  hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/InstantValidationTest.java
Labels: 6.1

#5381 HHH-15580 Emulate lt/gt/le/ge tuple-comparisons when unsupported
  hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
Labels: 6.1

#5383 HHH-15531 Use dense_rank instead of row_number when query uses distinct
  hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/SqmInsertStrategyHelper.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/TableBasedInsertHandler.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertSelectTests.java
Labels: 6.1

#5409 HHH-15590 Test that JdbcLiteralFormatter works for all supported java types
  hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/DateTimeUtils.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/UUIDJdbcType.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcLiteralFormatterUUIDData.java
  hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/LiteralRenderingTest.java
  hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/JUnitHelper.java
Labels: 6.1

#5413 HHH-15561 - Fixed and added test for issue
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/H2FinalTableIdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/H2IdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/IdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/id/insert/InsertSelectIdentityInsert.java
  hibernate-core/src/test/java/org/hibernate/orm/test/id/IdentityIdEntityTest.java
Labels: JIRA issue Test Case

#5415 HHH-15561 - Fixed and added test for issue
  hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/H2FinalTableIdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/H2IdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/dialect/identity/IdentityColumnSupport.java
  hibernate-core/src/main/java/org/hibernate/id/insert/InsertSelectIdentityInsert.java
  hibernate-core/src/test/java/org/hibernate/orm/test/id/IdentityIdEntityTest.java
Labels: 6.1

#5439 HHH-15619, HHH-15620 Expose HBM query configs through respective hints and don't mark transformed HBM model as metadata complete
  hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/internal/JPAXMLOverriddenAnnotationReader.java
  hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/Bar.java
  hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/BarPK.java
  hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmNamedQueryConfigurationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmOverridesAnnotation.hbm.xml
  hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmOverridesAnnotation.orm.xml
Labels: 6.1

#5441 HHH-15615 Add EDB PostgreSQL Advanced to test matrix and fix issues
  .github/workflows/contributor-build.yml
  Jenkinsfile
  ci/build.sh
  ci/database-start.sh
  docker_db.sh
  edb/Dockerfile
  edb/docker-entrypoint.sh
  gradle/databases.gradle
  gradle/java-module.gradle
  hibernate-core/hibernate-core.gradle
  hibernate-core/src/test/java/org/hibernate/orm/test/annotations/dataTypes/BasicOperationsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/always/GeneratedAlwaysTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/type/DateArrayTest.java
Labels: 6.1

#5443 Switch to HANA cloud instances
  Jenkinsfile
  ci/build.sh
  gradle/databases.gradle
  nightly.Jenkinsfile
Labels: hana

#5308 add DEBUG flag for saving of loaded entity as proxy
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
Labels: 6.1

#5319 add DEBUG flag save of loaded entity as proxy
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
Labels: 5.3
