Repository hibernate/hibernate-orm, pull requests merged in 2022-03, with the labels that each got.

#4857 Fix subquery throwing SqlTreeCreationException( Found un-correlated p…
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaSubqueryTest.java
Labels: 6.0

#4858 HHH-13694 fix numeric overflow exception for large sequence min values
  hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorLegacyImpl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorOracleDatabaseImpl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorTiDBDatabaseImpl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationImpl.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/extract/spi/SequenceInformation.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/OracleDialectSequenceInformationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/OracleSequenceInfoTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SequenceInformationTest.java
Labels: 6.0

#4859 HHH-15071 Apply type inference in SQM for like predicate and avoid NPE in query parameters
  hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQueryParameter.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmMemberOfPredicate.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ParameterTests.java
Labels: 6.0

#4861 HHH-15105 Fix NPE when access default query cache region statistics
  hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java
  hibernate-core/src/test/java/org/hibernate/test/cache/CacheRegionStatisticsTest.java
Labels: 5.6

#4862 HHH-15105 Test and fix for NPE when access default query cache region statistics
  hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cache/CacheRegionStatisticsTest.java
Labels: 6.0

#4867 HHH-15115 Deleting an entity with Joined inheritance and default schema set is throwing and error
  hibernate-core/src/main/java/org/hibernate/hql/spi/id/cte/AbstractCteValuesListBulkIdHandler.java
  hibernate-core/src/main/java/org/hibernate/hql/spi/id/global/GlobalTemporaryTableBulkIdStrategy.java
  hibernate-core/src/main/java/org/hibernate/hql/spi/id/local/LocalTemporaryTableBulkIdStrategy.java
  hibernate-core/src/main/java/org/hibernate/hql/spi/id/persistent/PersistentTableBulkIdStrategy.java
  hibernate-core/src/test/java/org/hibernate/test/inheritance/JoinedInheritanceDeletionTest.java
Labels: Ready for integration, 5.6

#4864 HHH-15113 Exception setting ParameterExpressions on Update Queries
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaUpdateImpl.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaCompiler.java
  hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ParameterExpressionImpl.java
  hibernate-core/src/test/java/org/hibernate/jpa/test/query/CriteriaUpdateWithParametersTest.java
Labels: 5.6

#4863 HHH-15113 - Exception setting ParameterExpressions on Update Queries
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CriteriaUpdateWithParametersTest.java
Labels: 6.0

#4709 HHH-15051 Add property mapping for target FK attributes for associations with id classes
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
  hibernate-core/src/test/java/org/hibernate/query/GroupByAliasTest.java
  hibernate-core/src/test/java/org/hibernate/test/hql/VirtualKeyManyToOnePropertyPathTest.java
Labels: 5.6

#4870 HHH-15115 Fix PostgreSQL SqmMultiTableMutationStrategy
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteDeleteHandler.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java
  hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceDeletionTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceWithDefaultSchemaDeletionTest.java
Labels: 6.0

#4876 Show an issue with BasicFormatterImpl
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/util/BasicFormatterTest.java
Labels: 6.0, Test case

#4884 HHH-15118 Fix duplicate ids with PooledOptimizer when sequence value is initialValue
  documentation/src/test/java/org/hibernate/userguide/envers/EntityTypeChangeAuditTest.java
  hibernate-core/src/main/java/org/hibernate/id/enhanced/PooledOptimizer.java
  hibernate-core/src/test/java/org/hibernate/id/enhanced/OptimizerUnitTest.java
  hibernate-core/src/test/java/org/hibernate/test/idgen/enhanced/forcedtable/PooledForcedTableSequenceTest.java
  hibernate-core/src/test/java/org/hibernate/test/idgen/enhanced/sequence/PooledSequenceTest.java
  hibernate-core/src/test/java/org/hibernate/test/idgen/enhanced/table/PooledTableTest.java
Labels: 5.6

#4885 HHH-14487 Fix usage of wrong Map in PropertyAccessStrategyMapImpl
  hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyMapImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/property/PropertyAccessStrategyMapTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/query/NativeSQLQueriesTest.java
Labels: 6.0

#4886 HHH-14487 Fix usage of wrong Map in PropertyAccessStrategyMapImpl
  hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyMapImpl.java
  hibernate-core/src/test/java/org/hibernate/property/PropertyAccessStrategyMapTest.java
  hibernate-core/src/test/java/org/hibernate/test/sql/hand/query/NativeSQLQueriesTest.java
Labels: 5.6

#4891 HHH-13135 Use FOR NO KEY UPDATE when locking in PostgreSQL
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockReference.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java
Labels: 6.0

#4920 Generator increment
  hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/idgenerator/SequenceGeneratorIncrementTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/idgenerator/TestEntity.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/idgenerator/sequence.hbm.xml
Labels: 6.0

#4927 HHH-15078 - Support for Tuple and SelectionQuery
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
Labels: 6.0
