Repository hibernate/hibernate-orm, pull requests merged in 2022-04, with the labels that each got.

#4948 HHH-14819 Add test for issue
  hibernate-core/src/test/java/org/hibernate/orm/test/limit/Oracle12LimitTest.java
Labels: 6.0

#4949 HHH-14819 Add test for issue
  hibernate-core/src/test/java/org/hibernate/test/limit/Oracle12LimitTest.java
Labels: 5.6

#4943 HHH-15106 - fk() HQL function
  hibernate-core/src/main/antlr/hql-sql.g
  hibernate-core/src/main/antlr/hql.g
  hibernate-core/src/main/antlr/sql-gen.g
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/SqlASTFactory.java
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
  hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FkRefNode.java
  hibernate-core/src/test/java/org/hibernate/orm/test/notfound/FkRefTests.java
Labels: 5.3

#4956 Gradle release script removed --protocol=28 for rsync
  hibernate-orm-build/src/main/java/org/hibernate/orm/docs/PublishTask.java
Labels: 6.0

#4957 Gradle release script removed --protocol=28 for rsync
  release/release.gradle
Labels: 5.6

#4958 Gradle release script removed --protocol=28 for rsync
  release/release.gradle
Labels: 5.3

#4961 Gradle changed uploadDocumentation rsync url and port
  hibernate-orm-build/src/main/java/org/hibernate/orm/docs/DocumentationPublishing.java
  hibernate-orm-build/src/main/java/org/hibernate/orm/docs/PublishTask.java
Labels: 6.0

#4960 Gradle changed uploadDocumentation rsync url and port
  release/release.gradle
Labels: 5.6

#4959 Gradle changed uploadDocumentation rsync url and port
  release/release.gradle
Labels: 5.3

#4963 HHH-15167 IllegalArgumentException occurred while calling setter for…
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/association/toone/CriteriaJoinFetchTest.java
Labels: 6.0

#4978 HHH-15221 fix a logging error in JdbcValuesCacheHit.java
  hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java
Labels: 6.0
