Repository hibernate/hibernate-orm, pull requests merged in 2022-01, with the labels that each got.

#4546 minor cleanups to the grammar
  hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
  hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
Labels: 6.0

#4547 reenable some LiteralTests
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LiteralTests.java
Labels: 6.0

#4552 add examples with treat()
  documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
  documentation/src/main/java/org/hibernate/userguide/model/Account.java
  documentation/src/main/java/org/hibernate/userguide/model/Call.java
  documentation/src/main/java/org/hibernate/userguide/model/CreditCardPayment.java
  documentation/src/main/java/org/hibernate/userguide/model/Payment.java
  documentation/src/test/java/org/hibernate/userguide/batch/BatchTest.java
  documentation/src/test/java/org/hibernate/userguide/criteria/CriteriaTest.java
  documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
  documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java
Labels: 6.0

#4553 enum + Java constant examples
  documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
  documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
Labels: 6.0

#4557 allow parameter in like escape
  hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeTest.java
Labels: 6.0

#4562 get rid of things named Ejb3
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedColumn.java
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedDiscriminatorColumn.java
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedJoinColumn.java
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
  hibernate-core/src/main/java/org/hibernate/cfg/ClassPropertyHolder.java
  hibernate-core/src/main/java/org/hibernate/cfg/CollectionPropertyHolder.java
  hibernate-core/src/main/java/org/hibernate/cfg/ColumnsBuilder.java
  hibernate-core/src/main/java/org/hibernate/cfg/ComponentPropertyHolder.java
  hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/DefaultComponentSafeNamingStrategy.java
  hibernate-core/src/main/java/org/hibernate/cfg/FkSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/IndexColumn.java
  hibernate-core/src/main/java/org/hibernate/cfg/IndexOrUniqueKeySecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/JoinedSubclassFkSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/PersistenceStandardEntityResolver.java
  hibernate-core/src/main/java/org/hibernate/cfg/PersistenceStandardNamingStrategy.java
  hibernate-core/src/main/java/org/hibernate/cfg/PkDrivenByDefaultMapsIdSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/PropertyHolder.java
  hibernate-core/src/main/java/org/hibernate/cfg/ToOneFkSecondPass.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/IdBagBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/ListBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/MapBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/TableBinder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cfg/annotations/CollectionBinderTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/joinedsubclass/JoinedSubclassWithImplicitDiscriminatorTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/namingstrategy/ejb3joincolumn/Tests.java
  hibernate-core/src/test/java/org/hibernate/test/annotations/AlternativeNamingStrategy.java
Labels: 6.0

#4595 remove the layer-breaking getLobCreator() methods from Hibernate class
  hibernate-core/src/main/java/org/hibernate/Hibernate.java
  hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/FetchGraphTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/ProxyDeletionTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/connections/HibernateCreateBlobFailedCase.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/lob/BlobLocatorTest.java
Labels: 6.0

#4604 add IdentifierLoadAccess.withReadOnly()
  hibernate-core/src/main/java/org/hibernate/IdentifierLoadAccess.java
  hibernate-core/src/main/java/org/hibernate/LockOptions.java
  hibernate-core/src/main/java/org/hibernate/loader/access/IdentifierLoadAccessImpl.java
Labels: 6.0

#4608 allow @Comment to apply at the class level
  hibernate-core/src/main/java/org/hibernate/annotations/Comment.java
  hibernate-core/src/main/java/org/hibernate/annotations/Table.java
  hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
  hibernate-core/src/main/java/org/hibernate/cfg/ColumnsBuilder.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/CommentTest.java
Labels: 6.0

#4619 Fix postLoad callback method calls
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/callback/listener/MultiListenersAppliedTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/callback/listener/PersonListener.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/callback/listener/orm.xml
Labels: 6.0

#4509 HHH-15000 Upgrade to Hibernate Commons Annotations 6.0.0.Beta1
  gradle/libraries.gradle
Labels: 6.0

#4637 Throw IllegalArgumentException when cannot resolve attribute names
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/IllegalArgumentExceptionTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/AbstractPathImplTest.java
Labels: 6.0

#4644 Throw IllegalArgumentException when the an attribute name is not reso…
  hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/IllegalArgumentExceptionTest.java
Labels: 6.0

#4638 Throw IllegalArgumentException for null Criteria literal value
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaLiteralValue.java
Labels: 6.0

#4645 Throw IllegalArgumentException when the an attribute name is not reso…
  hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/IllegalArgumentExceptionTest.java
Labels: 6.0

#4653 Fix MaskSensitiveInformationTest failure
  hibernate-core/src/test/java/org/hibernate/orm/test/internal/util/MaskSensitiveInformationTest.java
  hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java
Labels: 6.0

#4650 Fix CriteriaBuidler#locate() arguments order rendering
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CacheDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/IngresDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MaxDBDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
  hibernate-core/src/main/java/org/hibernate/dialect/function/LocatePositionEmulation.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaLiteralValue.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaLocateTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Labels: 6.0

#4657 Wip/6.0 tck locate 2
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CacheDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/IngresDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MaxDBDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
  hibernate-core/src/main/java/org/hibernate/dialect/function/LocatePositionEmulation.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/LocateTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Labels: 6.0

#4660 Fix criteria mod failing on derby
  hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/ModulusTest.java
Labels: 6.0

#4606 Fix converter issues
  hibernate-core/src/main/java/org/hibernate/metamodel/model/convert/internal/JpaAttributeConverterImpl.java
  hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/AttributeConverterTypeAdapter.java
  hibernate-core/src/main/java/org/hibernate/type/descriptor/java/IntegerJavaTypeDescriptor.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/Address.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/AgeConverter.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConverterExceptionsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConverterTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/Employee.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/Farm.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/Person.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ToDataBaseColumnThrowRuntimeExceptionConverter.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ToEntityAttributeThrowRuntimeExceptionConverter.java
Labels: 6.0

#4670 HHH-15044 Revert HHH-14826 fix because the provided test was wrong
  hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
  hibernate-core/src/test/java/org/hibernate/test/onetoone/cache/OneToOneCacheEnableSelectingTest.java
Labels: 5.6

#4672 Fix ArrayIndexOutOfBoundsException for CollectionJoin#on(Predicate ...)
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaPredicateTest.java
Labels: 6.0

#4673 HHH-15044 Revert HHH-14826 fix because the provided test was wrong
  hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
  hibernate-core/src/test/java/org/hibernate/test/onetoone/cache/OneToOneCacheEnableSelectingTest.java
Labels: 5.5

#4699 Remove some deprecations in org.hibernate.cfg
  hibernate-core/src/main/java/org/hibernate/boot/MetadataBuilder.java
  hibernate-core/src/main/java/org/hibernate/cfg/AttributeConverterDefinition.java
  hibernate-core/src/main/java/org/hibernate/cfg/ClassPropertyHolder.java
  hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
  hibernate-core/src/main/java/org/hibernate/cfg/PropertyContainer.java
  hibernate-core/src/main/java/org/hibernate/cfg/Settings.java
  hibernate-core/src/main/java/org/hibernate/cfg/annotations/TableBinder.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentArrayHolder.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentIdentifierBag.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentList.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSet.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSortedMap.java
  hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSortedSet.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
  hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/generics/ParameterizedAttributeConverterParameterTypeTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/inheritence/AttributeConverterOnSuperclassTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mappingexception/MappingExceptionTest.java
  hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseCoreFunctionalTestCase.java
Labels: 6.0

#4712 Fix tests and implement handling callable function hint for stored procedures
  hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
  hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureOutputsImpl.java
  hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java
  hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallFunctionReturnImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/procedure/OracleStoredProcedureTest.java
Labels: 6.0

#4713 Fix rendering of negated boolean expression predicate
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/CockroachSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmBooleanExpressionPredicate.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaIsFalseTest.java
Labels: 6.0

#4714 Fix Subquery#getCorrelatedJoins throws NPE when FromClause is null
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaGetCorrelatedJoinsTest.java
Labels: 6.0

#4708 Skip Criteria result type validation when JPA query compliance is ena…
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaWrongResultClassTest.java
Labels: 6.0

#4715 CriteriaQuery#getParameters() should not return parameters internall…
  hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/JpaCriteriaParameter.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/ValueBindJpaCriteriaParameter.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaGetParametersTest.java
Labels: 6.0

#4735 Fix Criteria#getResultType() returning Object class instead of null
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CrtiteriaGetResultTypeTest.java
Labels: 6.0

#4738 Fix Criteria Subquery#getSelection() returns null when it has not any…
  hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/RootEntityTypeModelTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/SubqueryGroupByTest.java
Labels: 6.0

#4752 Throw UnknownSqlResultSetMappingException for non existing StoreProce…
  hibernate-core/src/main/java/org/hibernate/procedure/internal/Util.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/StoreProcedureTest.java
Labels: 6.0

#4718 Jrenaat 6.0 deprecation removals
  documentation/src/main/asciidoc/userguide/chapters/bootstrap/Bootstrap.adoc
  hibernate-core/src/main/java/org/hibernate/DuplicateMappingException.java
  hibernate-core/src/main/java/org/hibernate/InstantiationException.java
  hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/JpaOrmXmlEventReader.java
  hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalSchema.java
  hibernate-core/src/main/java/org/hibernate/boot/registry/StandardServiceRegistryBuilder.java
  hibernate-core/src/main/java/org/hibernate/cache/internal/CollectionCacheInvalidator.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/WrappedNClob.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcCoordinator.java
  hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
  hibernate-core/src/main/java/org/hibernate/event/internal/PostDeleteEventListenerStandardImpl.java
  hibernate-core/src/main/java/org/hibernate/event/internal/PostInsertEventListenerStandardImpl.java
  hibernate-core/src/main/java/org/hibernate/event/internal/PostUpdateEventListenerStandardImpl.java
  hibernate-core/src/main/java/org/hibernate/event/spi/AbstractPreDatabaseOperationEvent.java
  hibernate-core/src/main/java/org/hibernate/event/spi/PostActionEventListener.java
  hibernate-core/src/main/java/org/hibernate/id/enhanced/OptimizerFactory.java
  hibernate-core/src/main/java/org/hibernate/integrator/spi/ServiceContributingIntegrator.java
  hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
  hibernate-core/src/test/java/org/hibernate/orm/test/collection/LoadEntityWithElementCollectionTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/event/entity/MergeListPreAndPostPersistTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/event/entity/MergeListPreAndPostPersistWithIdentityTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/events/LegacyPostCommitListenerTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/events/PostCommitListenerTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/sharedSession/SessionWithSharedConnectionTest.java
  hibernate-envers/src/main/java/org/hibernate/envers/event/spi/EnversPostDeleteEventListenerImpl.java
  hibernate-envers/src/main/java/org/hibernate/envers/event/spi/EnversPostInsertEventListenerImpl.java
  hibernate-envers/src/main/java/org/hibernate/envers/event/spi/EnversPostUpdateEventListenerImpl.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RegisterUserEventListenersTest.java
Labels: 6.0
