Repository hibernate/hibernate-orm, pull requests merged in 2023-04, with the labels that each got.

#6350 HHH-16429 WF SessionFactoryTestCase test fails
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
Labels: 6.2

#6449 HHH-15602 Fix bidirectional association management code
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/ManyToManyAssociationListTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToOneAssociationTest.java
Labels: 6.2

#6451 HHH-15602 Javassist implementation of proper bidirectional handling
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/PersistentAttributesEnhancer.java
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/PersistentAttributesHelper.java
Labels: 5.3

#6396 Backport HHH-16458 to branch 6.2 - JDBC statement is not closed when DeferredResultSetAccess fails to execute a query
  hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/QuerySqlExceptionTest.java
  hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/PreparedStatementSpyConnectionProvider.java
Labels: 6.2

#6422 HHH-16392 @Where annotation 6.0 migration guide chapter
  migration-guide.adoc
Labels: 6.0
