Repository hibernate/hibernate-orm, pull requests merged in 2023-10, with the labels that each got.

#7309 HHH-17139 Support Instant as revision timestamps
  hibernate-envers/src/main/java/org/hibernate/envers/AuditReader.java
  hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/RevisionInfoConfiguration.java
  hibernate-envers/src/main/java/org/hibernate/envers/exception/RevisionDoesNotExistException.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/RevisionTimestampData.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/reader/AuditReaderImpl.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionInfoQueryCreator.java
  hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionTimestampValueResolver.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/reventity/CustomInstantRevEntity.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/reventity/CustomInstantRevEntityTest.java
Labels: 6.4

#7242 [HHH-17065] Unique Index on PrimaryKey orders primary key columns
  documentation/src/main/asciidoc/userguide/chapters/schema/Schema.adoc
  hibernate-core/src/main/java/org/hibernate/boot/model/relational/ColumnOrderingStrategyStandard.java
  hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
  hibernate-core/src/main/java/org/hibernate/mapping/PrimaryKey.java
  hibernate-core/src/main/java/org/hibernate/mapping/Table.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/uniqueconstraint/CompositePrimaryKeyColumnOrderTest.java
Labels: 6.4

#7262 HHH-17153: Upgrade antlr4 to version 4.13.0
  settings.gradle
Labels: 6.4

#7438 Fix HANA test failures
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
  hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/CommentGenerationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/TableCommentTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/CollectionOfSoftDeleteTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/SimpleSoftDeleteTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/ToOneTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/collections/FetchLoadableTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/collections/UsageTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/converter/ConvertedSoftDeleteTests.java
  hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/converter/reversed/ReversedSoftDeleteTests.java
Labels: hana, 6.4

#7450 HHH-16595 Optimize away nested table group joins when possible
  hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/PluralAttributeMapping.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/WhereRestrictable.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
  hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CollectionTableGroup.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/BagInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/MapInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SetInitializer.java
  hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java
  hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/EntityGraphLoadPlanBuilderTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/JoinTableOptimizationTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/CompareEntityValuedPathsTest.java
Labels: 6.3

#7449 HHH-17322 Allow custom generators to determine timing based on current entity state
  hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
  hibernate-core/src/main/java/org/hibernate/generator/Generator.java
  hibernate-core/src/main/java/org/hibernate/id/factory/internal/IdentifierGeneratorUtil.java
  hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
  hibernate-core/src/main/java/org/hibernate/mapping/Component.java
  hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
  hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
  hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
  hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/MixedTimingGeneratorsTest.java
Labels: 6.4

#7471 HHH-17351 Add missing basic type registration after changing preferred jdbc type
  hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
Labels: 6.3
