Repository hibernate/hibernate-orm, pull requests merged in 2023-03, with the labels that each got.

#6196 Add migration guide section about entity path comparison validation changes
  migration-guide.adoc
Labels: 6.0

#6197 HHH-15766 UNION query doesn't preserve the original parenthesis
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
  hibernate-core/src/main/java/org/hibernate/internal/util/collections/Stack.java
  hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java
  hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
  hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/HqlUnionTest.java
Labels: cockroachdb, hana

#6208 Fix date truncation for HANA
  hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
Labels: hana

#6297 Backport of reproducer for HHH-16378 SQM fails to resolve target type of association defined in mappersuperclass with generics
  hibernate-core/src/test/java/org/hibernate/orm/test/association/GenericAssociationTest.java
Labels: 5.6
