Repository hibernate/hibernate-orm, pull requests merged in 2025-07, with the labels that each got.

#9927 HHH-19297 Register SingleStore json functions to community SingleStoreDialect
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreDialect.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreSqlAstTranslator.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayAggFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayAppendFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayInsertFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonExistsFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonMergepatchFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonObjectAggFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonObjectFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonQueryFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonRemoveFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonSetFunction.java
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonValueFunction.java
Labels: 7.1

#10614 Adjust the changelog to match what was release
  changelog.txt
Labels: 7.0

#10608 [6.6] HHH-16253 - Schema Validation Failure With Audited (N)Clob Column
  hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lob/LargeObjectMappingTest.java
Labels: 6.6

#10607 [7.0] HHH-16253 - Schema Validation Failure With Audited (N)Clob Column
  hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
  hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lob/LargeObjectMappingTest.java
Labels: 7.0

#10640 [7.0] HHH-19654 Upgrade hibernate-models to 1.0.1
  settings.gradle
Labels: 7.0
