Repository hibernate/hibernate-orm, pull requests merged in 2025-06, with the labels that each got.

#10280 HHH-19518 Make hibernate-maven-plugin configuration parameters non-readonly
  tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/HibernateEnhancerMojo.java
Labels: 7.1

#10293 [6.2] Limit disk usage of TCK reports
  ci/jpa-3.1-tck.Jenkinsfile
Labels: 6.2

#10285 HHH-19446 HHH-18633 `hibernate-scan-jandex` migration guide
  migration-guide.adoc
Labels: 7.0

#10297 [7.0] HHH-19518 Make hibernate-maven-plugin configuration parameters non-readonly
  tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/HibernateEnhancerMojo.java
Labels: 7.0

#10313 [6.6] implement equals() / hashCode() for NativeQueryConstructorTransformer
  hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java
Labels: 6.6

#10330 Move to Central publishing 7.0
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  local-build-plugins/src/main/groovy/local.publishing.gradle
Labels: 7.0

#10328 Move to Central publishing 6.4
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  gradle/publishing-pom.gradle
Labels: 6.4

#10327 Move to Central publishing 6.2
  ci/release/Jenkinsfile
  gradle/publishing-pom.gradle
Labels: 6.2

#10326 Move to Central publishing
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  gradle/publishing-repos.gradle
Labels: 5.6

#10325 Move to Central publishing 5.3
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  gradle/publishing-repos.gradle
Labels: 5.3

#10350 [7.0] Allow builds with test jdk versions on PRs with custom labels
  Jenkinsfile
Labels: 7.0

#10352 HHH-19547 backport to 7.0
  hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
Labels: 7.0

#10361 Skip jacoco instrumentation/coverage in jenkins builds
  Jenkinsfile
  local-build-plugins/src/main/groovy/local.java-module.gradle
Labels: jdk

#10403 [6.6] HHH-19560 Remove TupleTransformer and ResultListTransformer from interpretation caching
  hibernate-core/src/main/java/org/hibernate/dialect/function/SqlFunction.java
  hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
  hibernate-core/src/main/java/org/hibernate/query/sql/spi/SelectInterpretationsKey.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
  hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
Labels: 6.6

#10407 [6.2] HHH-19573 Special case primitive type names for plural basic types
  hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java
  hibernate-core/src/main/java/org/hibernate/type/BasicCollectionType.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ByteArrayMappingTests.java
Labels: 6.2

#10408 [6.6] HHH-19573 Special case primitive type names for plural basic types
  hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java
  hibernate-core/src/main/java/org/hibernate/type/BasicCollectionType.java
  hibernate-core/src/main/java/org/hibernate/type/ConvertedBasicArrayType.java
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ByteArrayMappingTests.java
Labels: 6.6

#10418 [7.0] HHH-19577 Avoid duplicate stack map frames for SetPropertyValues
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
Labels: 7.0

#10417 [6.2] HHH-19577 Avoid duplicate stack map frames for SetPropertyValues
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
Labels: 6.2
