Repository hibernate/hibernate-orm, pull requests merged in 2025-05, with the labels that each got.

#10119 HHH-19341 Backport JReleaser config to 6.6
  build.gradle
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  gradle/published-java-module.gradle
  hibernate-platform/hibernate-platform.gradle
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.6

#10147 HHH-19341 Move publication repositories configuration to a more common gradle file
  gradle/published-java-module.gradle
  gradle/publishing-pom.gradle
Labels: 6.6

#10121 HHH-19341 Backport JReleaser config to 6.2
  build.gradle
  ci/release/Jenkinsfile
  gradle/published-java-module.gradle
  gradle/publishing-pom.gradle
  hibernate-platform/hibernate-platform.gradle
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.2

#10120 HHH-19341 Backport JReleaser config to 6.4
  build.gradle
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  gradle/published-java-module.gradle
  gradle/publishing-pom.gradle
  hibernate-platform/hibernate-platform.gradle
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.4

#10157 HHH-19341 Fix hibernate-orm-modules snapshot release issue
  hibernate-orm-modules/hibernate-orm-modules.gradle
Labels: 5.3

#10177 HHH-19472: native queries can return Object[]
  hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryArrayTransformer.java
  hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/hql/SingleSelectionArrayResultTest.java
Labels: 6.6

#10170 HHH-19473: Use asDefined type when enhancing BiDirectional Associations to resolve issue with mismatched generated method signatures.
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java
  hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingAndParameterizedInheritanceTest.java
Labels: 6.6

#10163 Make bytecode test engine backwards compatible with older JUnit versions
  hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedEngineDescriptor.java
  hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java
Labels: 6.6

#9626 HHH-18957 - Add test for issue
  hibernate-core/src/test/java/org/hibernate/orm/test/records/ElementCollectionOfRecordsTest.java
  hibernate-core/src/test/java/org/hibernate/orm/test/records/GenericEmbeddedIdRecordTest.java
Labels: JIRA issue Test Case
