Repository hibernate/hibernate-orm, pull requests merged in 2025-10, with the labels that each got.

#8890 HHH-17017 Hibernate 6 cannot read VARCHAR column as INT
  hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/EnumAndColumnDefinitionTest.java
Labels: Test case

#11012 HHH-19800 Migrate to release scripts for documentation publishing
  ci/release/Jenkinsfile
  gradle/published-java-module.gradle
  local-build-plugins/build.gradle
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DescriptorAccess.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DocumentationPublishing.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DocumentationPublishingPlugin.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/GenerateDescriptorTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ProjectDocumentationDescriptor.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishDescriptorTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishMigrationGuide.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ReleaseFamilyDocumentation.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ReleaseFamilyIdentifierMarshalling.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/RsyncHelper.java
  release/release.gradle
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.6

#11014 HHH-19800 Migrate to release scripts for documentation publishing
  ci/release/Jenkinsfile
  gradle/published-java-module.gradle
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DescriptorAccess.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DocumentationPublishing.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/DocumentationPublishingPlugin.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/GenerateDescriptorTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ProjectDocumentationDescriptor.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishDescriptorTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishMigrationGuide.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishTask.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ReleaseFamilyDocumentation.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/ReleaseFamilyIdentifierMarshalling.java
  local-build-plugins/src/main/java/org/hibernate/orm/docs/RsyncHelper.java
  release/release.gradle
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.2

#11028 HHH-19800 Migrate to release scripts for documentation publishing
  release/release.gradle
Labels: 5.6

#11029 HHH-19800 Migrate to release scripts for documentation publishing
  release/release.gradle
Labels: 5.3

#10950 Add methods and change method access for Hibernate Reactive
  hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
  hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataPojoImpl.java
  hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java
  hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java
  hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
Labels: 7.1

#11069 HHH-19767 Include license file in the META-INF of published artifacts
  local-build-plugins/src/main/groovy/local.java-module.gradle
Labels: 7.1

#11072 [7.1] Backport: HHH-19629 Hibernate Processor may fail when repository method parameter has more than one annotation (e.g. multiple constraints) / HHH-19630 Hibernate Processor may fail if the return type is a single entity and annotated with multiple annotations
  tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/constraint/DataTest.java
  tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/constraint/MyConstrainedRepository.java
  tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/constraint/MyEntity.java
  tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
Labels: 7.1

#10490 HHH-19137 - @NamedEntityGraph entity loading fails with AssertionError on entity model with multiple collections and composite keys
  hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/LoadEntityGraphWithCompositeKeyCollectionsTest.java
Labels: JIRA issue Test Case

#11083 Update the changelog to match the released tasks
  changelog.txt
Labels: 7.1

#11084 Update the changelog to match the released JIRAs
  changelog.txt
Labels: 6.6

#11081 Fix check Gradle task graph contains task
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.6

#11073 Add a publish plugin task dependency to releasePerform
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.6

#11075 Add a publish plugin task dependency to releasePerform
  tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Labels: 6.2
