Repository hibernate/hibernate-orm, pull requests merged in 2025-04, with the labels that each got.

#9978 Backport to 6.6: Test the ci-commiter before checking the release type (manual/automatic)
  ci/release/Jenkinsfile
Labels: 6.6

#9995 Avoid non-functioning TIMESTAMP_WITH_TIMEZONE type code on sybase
  hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
  hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
Labels: sybase

#9979 Backport to 6.4: Test the ci-commiter before checking the release type (manual/automatic)
  ci/release/Jenkinsfile
Labels: 6.4

#9980 Backport to 6.2: Test the ci-commiter before checking the release type (manual/automatic)
  ci/release/Jenkinsfile
Labels: 6.2

#9930 HHH-19036 Process all filters before going through classes
  hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
  hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
  hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterDefinitionOrderTest.java
Labels: 6.6

#10003 HIB-140 Switch to develocity.commonhaus.dev instance
  README.adoc
  gradle/gradle-enterprise.gradle
Labels: 6.4
